### ISSUE TITLE
AnyEqualityTest fails on JDK17+

### ISSUE THREAD

**Issue by dmatej** [eclipse-ee4j/orb#191]
* Passed on JDK11
* Failed on any JDK 17+ I have including 23
```
[ERROR] com.sun.corba.ee.impl.corba.AnyEqualityTest.twoAnysContainingTheSameTypecode_areEqual -- Time elapsed: 1.239 s <<< ERROR!
java.lang.UnsupportedOperationException: WARNING: GMBALTLIB00004: Multiple upper bounds not supported on S
at jdk.proxy2/jdk.proxy2.$Proxy48.multipleUpperBoundsNotSupported(Unknown Source)
at org.glassfish.gmbal.typelib.TypeEvaluator$TypeEvaluationVisitor.lookup(TypeEvaluator.java:653)
at org.glassfish.gmbal.typelib.TypeEvaluator$TypeEvaluationVisitor.visitTypeVariable(TypeEvaluator.java:591)
at org.glassfish.gmbal.typelib.TypeEvaluator$TypeEvaluationVisitor.evaluateType(TypeEvaluator.java:415)
at org.glassfish.gmbal.typelib.TypeEvaluator$TypeEvaluationVisitor.visitMethodDeclaration(TypeEvaluator.java:572)
at org.glassfish.gmbal.typelib.TypeEvaluator$TypeEvaluationVisitor$4.evaluate(TypeEvaluator.java:738)
at org.glassfish.gmbal.typelib.TypeEvaluator$TypeEvaluationVisitor$4.evaluate(TypeEvaluator.java:734)
at org.glassfish.pfl.basic.algorithm.Algorithms.map(Algorithms.java:73)
at org.glassfish.pfl.basic.algorithm.Algorithms.map(Algorithms.java:96)
```

**Comment by pzygielo** [comment]
Sounds like https://github.com/eclipse-ee4j/orb/issues/128

https://github.com/eclipse-ee4j/orb/issues/128#issuecomment-1074418657
